openapi: "3.1.0"
info:
  title: "A shopping list API"
  description: "This is a shopping list API that includes authentication with OIDC, shared lists and all that."
  version: 0.1.0
paths:
  '/lists':
    get:
      summary: Returns a list of the user's shopping lists
      description: Returns a list of shopping lists for the current user. The user is identified by the authentication token.
      operationId: getShoppingLists
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
        default:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      
components:
  schemas:
    Error:
      type: object
      required:
        - rawMessage
        - prettyMessage
      properties:
        rawMessage:
          type: string
          description: The raw error message from whatever error occurred in the code. May be null.
          nullable: true
          readOnly: true
        prettyMessage:
          type: string
          description: The error message primarily displayed to the user.
          readOnly: true
  
    ShoppingList:
      type: object
      required:
        - creatorId
        - items
      properties:
        creatorId:
          type: string
          description: The person who created this shopping list
          format: uuid
        items:
          type: array
          items:
            $ref: '#/components/schemas/ShoppingListItem'
        totalPriceEstimate:
          type: number
          nullable: true
          description: An estimation of the price of the entire shopping list
            
    ShoppingListItem:
      type: object
      required:
        - name
        - creatorId
      properties:
        creatorId:
          type: string
          description: The person who added this item to the list
          format: uuid
        name:
          type: string
          description: The name of the item
        priceEstimate:
          nullable: true
          type: number
          description: An estimation of the price of the item
      
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
